FROM wordpress:5.8.3-php7.4-fpm-alpine

WORKDIR /var/www/html

# nano
# RUN apt-get install -y nano bash curl

# mysql-client
# RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable pdo_mysql

# xdebug
# RUN pecl install xdebug-3.1.6 \
#     && docker-php-ext-enable xdebug
# RUN  echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
#     && echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
#     && echo "xdebug.discover_client_host=1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
#     # && echo "xdebug.client_host=172.25.0.1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini


# CMD php -S 0.0.0.0:3000