FROM php:7.4-fpm

WORKDIR /var/www/html

# nano
RUN apt update && apt install -y nano bash curl

# mysql-client
RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable pdo_mysql

COPY . .